name: Install Dependencies

runs:
  using: composite

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install PNPM
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Get PNPM Cache Directory
      id: pnpm-cache
      shell: bash
      run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - name: Setup PNPM Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile