
import { Controller, Get } from '../app/app.decorator';
import { MetricData } from './metric.dto';
import { MetricService } from './metric.service';

@Controller('metrics')
export class MetricController {

  public constructor(
    private readonly metricService: MetricService,
  ) { }

  @Get({
    title: 'Read Metrics',
    description: 'Scraping endpoint for metrics generated by Prometheus client.',
    contentType: 'text/plain',
    schema: String,
  })
  public getMetrics(): Promise<string> {
    return this.metricService.readMetrics();
  }

  @Get('json', {
    title: 'Read Metrics (JSON)',
    description: 'Scraping endpoint for metrics generated by Prometheus client in JSON format.',
    schema: [ MetricData ],
  })
  public getMetricsJson(): Promise<MetricData[]> {
    return this.metricService.readMetricsJson();
  }

}
