import { Query } from '@nestjs/common';
import { metric } from 'prom-client';

import { Controller, Get } from '../app/app.decorator';
import { MetricData, MetricReadDto } from './metric.dto';
import { MetricService } from './metric.service';

@Controller('metrics', {
  tags: [ 'Application' ],
})
export class MetricController {

  public constructor(
    private readonly metricService: MetricService,
  ) { }

  @Get({
    operationId: 'Read Metrics',
    description: 'Scraping endpoint for metrics generated by Prometheus client.',
    produces: [ 'text/plain', 'application/json' ],
    response: { type: [ MetricData ] },
  })
  public getMetrics(@Query() query: MetricReadDto): Promise<string | metric[]> {
    const { json } = query;
    return this.metricService.readMetrics(json);
  }

}
