export enum SchemaSyncStatus {
  UP_TO_DATE = 'UP_TO_DATE',
  MIGRATION_SUCCESSFUL = 'MIGRATION_SUCCESSFUL',
  MIGRATION_FAILED = 'MIGRATION_FAILED',
}

export enum SchemaInjectionToken {
  MODULE_ID = 'MODULE_ID',
  MODULE_OPTIONS = 'MODULE_OPTIONS',
}
