version: '2.1'

networks:
  monitoring:
    driver: bridge

services:
  # Grafana - Centralized analytics vizualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - monitoring

  # Loki - Log aggregation system
  loki:
    image: grafana/loki
    container_name: loki
    user: root
    ports:
      - 3100:3100
    expose:
      - 3100
    networks:
      - monitoring
    command:
      - --config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki:/etc/loki

  # Prometheus - Metrics scraping and record in real-time database
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  # Pushgateway - Metrics gateway for pushing instead of scraping
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring
