version: '2.1'

networks:
  monitoring:
    driver: bridge

services:
  # Grafana - Centralized analytics vizualization
  grafana:
    image: grafana/grafana:8.4.6
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - monitoring

  # Loki - Log aggregation system
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - monitoring
    command:
      - --config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki:/etc/loki

  # Prometheus - Metrics scraping and timeseries database
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  # Pushgateway - Gateway for pushing metrics providing centralized scraping
  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring

  # Tempo - Distributed tracing back-end with object storage
  tempo:
    image: grafana/tempo:1.3.2
    container_name: tempo
    ports:
      - 55681:55681
      - 3200:3200
    networks:
      - monitoring
    command:
      - --config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./tempo:/etc/tempo
