export enum OrmStoreKey {
  ENTITY_MANAGER = 'ORM_ENTITY_MANAGER',
  COMMIT_PENDING = 'COMMIT_PENDING',
}

export enum OrmInjectionToken {
  ORM_MODULE_OPTIONS = 'ORM_MODULE_OPTIONS',
  ORM_PROVIDER_OPTIONS = 'ORM_PROVIDER_OPTIONS',
  ORM_SCHEMA_OPTIONS = 'ORM_SCHEMA_OPTIONS',
}

export enum OrmQueryOrder {
  ASC = 'ASC',
  DESC = 'DESC',
}
