name: Publish New Release to NPM
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Publish New Release to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint Check
        run: npm run lint

      - name: Execute Unit Tests
        run: npm run test

      - name: Build Distributable Package
        run: npm run build

      - name: Publish Package to NPM
        run: npx semantic-release
