name: Publish New Release to NPM
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Publish New Release to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile

      - name: Run Lint Check
        run: pnpm run lint

      - name: Execute Unit Tests
        run: pnpm run test

      - name: Build Distributable Package
        run: pnpm run build

      - name: Publish Package to NPM
        run: |
          npm i -g @semantic-release/changelog @semantic-release/git semantic-release
          npx semantic-release
